#!/usr/bin/env zsh

# To make the wrapper transparent (i.e., using a script called 'cirrus' to take
# precedence over the 'cirrus' binary, locating the original cirrus binary via
# 'which' requires removing the path the cirrus script resides in from the PATH
# variable used by 'which'.
cirrus_bin=$(env PATH=$(echo "$PATH" | tr ":" "\n" | grep -v $(dirname "$0") | tr "\n" ":") which cirrus)

# Environment variables set by direnv to unset (to hide from Docker envs)
unset_vars=("CONFIG_SHELL" "CC" "CXX" "AR" "ACLOCAL_PATH")

unset_command=("env")
for var in "${unset_vars[@]}"; do
    unset_command+=("-u" "$var")
done

# Make users aware that a wrapper is being used
log_bold() {
    echo -e "\e[1m$1\e[0m"
}
log_bold "cirrus wrapper: running $unset_command $cirrus_bin $@"

$unset_command $cirrus_bin "$@"
