#!/usr/bin/env zsh

is_git_repo() {
    git rev-parse --is-inside-work-tree >/dev/null 2>&1
}

is_bitcoin_repo() {
    local remote_url=$(git remote get-url origin)
    [[ "$remote_url" =~ '/bitcoin.git$' ]]
}

if [ "$#" -ne 2 ]; then
    echo "Usage: $0 PR_NUMBER BRANCH_NAME"
    exit 1
fi

if ! is_git_repo; then
    echo "Error: This script must be run within a git repository."
    exit 1
fi

if ! is_bitcoin_repo; then
    echo "Error: This script must be run within a Bitcoin Core repository clone."
    exit 1
fi

PR_NUMBER=$1
BRANCH_NAME=$2

git fetch origin pull/$PR_NUMBER/head:$BRANCH_NAME
git checkout $BRANCH_NAME
echo "Successfully checked out PR #$PR_NUMBER into $BRANCH_NAME."
git branch --show-current
